export const SocketEvents = {
  CONTEST_STARTED: 'contest:started',
  QUESTION_CHANGED: 'session:question_changed',
  QUESTION_DETAIL: 'session:question_detail',
  TIMER_STARTED: 'timer:started',
  TIMER_PAUSED: 'timer:paused',
  TIMER_RESET: 'timer:reset',
  TIMER_EXPIRED: 'timer:expired',
  ANSWER_REVEALED: 'answer:revealed',
  SCORES_UPDATED: 'scores:updated',
  SCORE_LOGGED: 'score:logged',
  CONTEST_FINISHED: 'contest:finished',
  SYNC_FULL_STATE: 'sync:full_state',
  HOST_NEXT_QUESTION: 'host:next_question',
  HOST_TIMER_CONTROL: 'host:timer_control',
  HOST_REVEAL_ANSWER: 'host:reveal_answer',
  JUDGE_SCORE: 'judge:score',
  JUDGE_REVERT_SCORE: 'judge:revert_score',
  SYNC_REQUEST: 'sync:request_full_state',
} as const;
