#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
FORCE_ENV=0

usage() {
  cat <<'EOF'
Usage:
  bash scripts/deploy.sh [--force-env]

Environment overrides (optional):
  APP_HOST APP_SCHEME APP_PORT
  MONGO_ROOT_USERNAME MONGO_ROOT_PASSWORD MONGO_DATABASE MONGODB_URI
  JWT_SECRET JWT_EXPIRES_IN JWT_REFRESH_EXPIRES_IN
  SMTP_HOST SMTP_PORT SMTP_USER SMTP_PASSWORD EMAIL_FROM EMAIL_SECURE
  ALLOWED_EMAIL_DOMAINS CORS_ORIGINS FRONTEND_URL

Examples:
  APP_HOST=contest.mareate.com APP_SCHEME=https APP_PORT=80 \
  SMTP_USER=admin@example.com SMTP_PASSWORD='your-smtp-pass' \
  EMAIL_FROM='BusyBee <admin@example.com>' \
  bash scripts/deploy.sh

  # Regenerate .env from current overrides:
  bash scripts/deploy.sh --force-env
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force-env)
      FORCE_ENV=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

require_cmd docker
require_cmd openssl
require_cmd curl

if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose is not available. Please install Docker Compose v2." >&2
  exit 1
fi

build_public_url() {
  local scheme="$1"
  local host="$2"
  local port="$3"

  if [[ "$scheme" == "http" && "$port" == "80" ]]; then
    printf "%s://%s" "$scheme" "$host"
    return
  fi
  if [[ "$scheme" == "https" && "$port" == "443" ]]; then
    printf "%s://%s" "$scheme" "$host"
    return
  fi
  printf "%s://%s:%s" "$scheme" "$host" "$port"
}

escape_env_value() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf "%s" "$value"
}

write_kv() {
  local key="$1"
  local value="$2"
  printf '%s="%s"\n' "$key" "$(escape_env_value "$value")"
}

generate_env() {
  local app_host="${APP_HOST:-contest.mareate.com}"
  local app_scheme="${APP_SCHEME:-https}"
  local app_port="${APP_PORT:-80}"

  if [[ "$app_scheme" != "http" && "$app_scheme" != "https" ]]; then
    echo "APP_SCHEME must be http or https (current: $app_scheme)" >&2
    exit 1
  fi

  if ! [[ "$app_port" =~ ^[0-9]+$ ]]; then
    echo "APP_PORT must be an integer (current: $app_port)" >&2
    exit 1
  fi

  local frontend_url="${FRONTEND_URL:-$(build_public_url "$app_scheme" "$app_host" "$app_port")}"
  local cors_origins="${CORS_ORIGINS:-$frontend_url}"

  local mongo_root_username="${MONGO_ROOT_USERNAME:-busybee}"
  local mongo_root_password="${MONGO_ROOT_PASSWORD:-$(openssl rand -hex 16)}"
  local mongo_database="${MONGO_DATABASE:-busybee}"
  local mongodb_uri="${MONGODB_URI:-mongodb://${mongo_root_username}:${mongo_root_password}@mongo:27017/${mongo_database}?authSource=admin}"

  local jwt_secret="${JWT_SECRET:-$(openssl rand -hex 48)}"
  local jwt_expires_in="${JWT_EXPIRES_IN:-7d}"
  local jwt_refresh_expires_in="${JWT_REFRESH_EXPIRES_IN:-30d}"

  local smtp_host="${SMTP_HOST:-smtp.exmail.qq.com}"
  local smtp_port="${SMTP_PORT:-465}"
  local smtp_user="${SMTP_USER:-}"
  local smtp_password="${SMTP_PASSWORD:-}"
  local email_secure="${EMAIL_SECURE:-true}"
  local allowed_email_domains="${ALLOWED_EMAIL_DOMAINS:-}"
  local email_from="${EMAIL_FROM:-BusyBee <${smtp_user}>}"

  if [[ -z "$smtp_user" || -z "$smtp_password" ]]; then
    cat >&2 <<'EOF'
SMTP_USER or SMTP_PASSWORD is empty.
This project only supports magic-link login right now, so SMTP is required.
Re-run with SMTP_USER/SMTP_PASSWORD set.
EOF
    exit 1
  fi

  if [[ "$email_from" != *"$smtp_user"* ]]; then
    echo "EMAIL_FROM must contain SMTP_USER address to satisfy provider requirements." >&2
    echo "SMTP_USER=${smtp_user}" >&2
    echo "EMAIL_FROM=${email_from}" >&2
    exit 1
  fi

  umask 077
  : > "$ENV_FILE"
  {
    echo "# Generated by scripts/deploy.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    write_kv APP_HOST "$app_host"
    write_kv APP_SCHEME "$app_scheme"
    write_kv APP_PORT "$app_port"
    write_kv NODE_ENV "production"
    write_kv PORT "3001"
    write_kv MONGO_ROOT_USERNAME "$mongo_root_username"
    write_kv MONGO_ROOT_PASSWORD "$mongo_root_password"
    write_kv MONGO_DATABASE "$mongo_database"
    write_kv MONGODB_URI "$mongodb_uri"
    write_kv JWT_SECRET "$jwt_secret"
    write_kv JWT_EXPIRES_IN "$jwt_expires_in"
    write_kv JWT_REFRESH_EXPIRES_IN "$jwt_refresh_expires_in"
    write_kv CORS_ORIGINS "$cors_origins"
    write_kv FRONTEND_URL "$frontend_url"
    write_kv SMTP_HOST "$smtp_host"
    write_kv SMTP_PORT "$smtp_port"
    write_kv SMTP_USER "$smtp_user"
    write_kv SMTP_PASSWORD "$smtp_password"
    write_kv EMAIL_FROM "$email_from"
    write_kv EMAIL_SECURE "$email_secure"
    write_kv ALLOWED_EMAIL_DOMAINS "$allowed_email_domains"
  } >> "$ENV_FILE"
}

cd "$ROOT_DIR"

if [[ ! -f "$ENV_FILE" || "$FORCE_ENV" -eq 1 ]]; then
  generate_env
  echo "Generated ${ENV_FILE}"
else
  echo "Using existing ${ENV_FILE} (pass --force-env to regenerate)"
fi

# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

APP_PORT="${APP_PORT:-80}"
APP_HOST="${APP_HOST:-contest.mareate.com}"
APP_SCHEME="${APP_SCHEME:-https}"
FRONTEND_URL="${FRONTEND_URL:-$(build_public_url "$APP_SCHEME" "$APP_HOST" "$APP_PORT")}"

if ! [[ "$APP_PORT" =~ ^[0-9]+$ ]]; then
  echo "APP_PORT must be an integer in ${ENV_FILE}." >&2
  exit 1
fi

if [[ -z "${SMTP_USER:-}" || -z "${SMTP_PASSWORD:-}" ]]; then
  echo "SMTP_USER/SMTP_PASSWORD cannot be empty in ${ENV_FILE}." >&2
  exit 1
fi

if [[ "${EMAIL_FROM:-}" != *"${SMTP_USER}"* ]]; then
  echo "EMAIL_FROM must contain SMTP_USER in ${ENV_FILE}." >&2
  exit 1
fi

docker compose up -d --build

echo "Deployment started. Waiting for health check..."
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${APP_PORT}/healthz" >/dev/null 2>&1; then
    echo "Health check passed: http://127.0.0.1:${APP_PORT}/healthz"
    echo "Open: ${FRONTEND_URL}"
    exit 0
  fi
  sleep 2
done

echo "Health check timeout. Check logs with: docker compose logs --tail=200" >&2
exit 1
